#############################################################################
# gitlab-runner:docker executor options
image: chapeiro/pelago-build:cuda11.1-llvm11

#############################################################################
variables:
 GIT_SUBMODULE_STRATEGY: recursive

#############################################################################
stages:
 - Code quality         # Environment configuration

 - Configure            # Environment configuration

 - Build                # Build the project

 - Install              # Install the software so it can be run for tests

 - Test                 # Functional tests

 - Benchmark            # Performance tests (need to be tagged in order to be
                        # run on a noise-free system)

 - Package              # Create archives to be installed

 - Publish              # Publish the packages

 - Build Profile        # Build the project with profiling information

 - Profile              # Profile using known workload

#############################################################################
# Helper Templates

before_script:
 # TODO: we should probably remove the next lines and fix that in executor
 - ln -s /data/ssbm100 inputs/ssbm100
 - ln -s /data/tpch1 inputs/tpch1

# after_script:
#  - true


#----------------------------------------------------------------------------
# Caching policies templates

.cache: &cache
 tags:
  - pelago
 cache:
  key: "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
  paths:
   - src/panorama
   - src/planner
   - src/SQLPlanner

.cache: &cache_profile
 cache:
  key: "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}-profile"
  paths:
   - src/panorama
   - src/planner
   - src/SQLPlanner

#----------------------------------------------------------------------------
# Execution restrictions templates
.restrict_precommit: &restrict_precommit
 except:
  - tags

.restrict_postcommit: &restrict_postcommit
 only:
  - master
  - tags

.restrict_latest: &restrict_latest
 except:
  - tags
 only:
  - master

.restrict_release: &restrict_release
 only:
  - tags

#----------------------------------------------------------------------------
# Job templates
.test: &test
 stage: Test
 cache:
  policy: pull
 <<: *cache
 <<: *restrict_precommit

.benchmark: &benchmark
 stage: Benchmark
 cache:
  policy: pull
 <<: *cache

#############################################################################
# Example jobs
#----------------------------------------------------------------------------

#----------------------------------------------------------------------------

codestyle:
 stage: Code quality
 script:
  # clang-format comes from the llvm repo: https://apt.llvm.org/
  # remember to update it every time we pop the LLVM version!
  # if grep returns an error, it didn't find a match, which is OK for us
  - find . \( -name '*.cpp' -o -name '*.hpp' -o -name '*.cu' -o -name '*.cuh' \) | xargs -n1 clang-format -output-replacements-xml --style=file | grep "replacement " || exit 0
  # otherwise, print message and exist with error code
  - echo "Non conforming format"
  - exit 1
 <<: *cache
 <<: *restrict_precommit

licenses:
 stage: Code quality
 script:
  - python tools/check_licenses.py
 <<: *cache
 <<: *restrict_precommit

configure:
 stage: Configure
 script:
  - cache_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
  - mkdir -p ${cache_path}/cmake-build-debug
  - export CWD=$(pwd)
  - cd ${cache_path}/cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=opt -G "CodeBlocks - Unix Makefiles" $CWD
  - echo "Configure... done"
 <<: *cache
 <<: *restrict_precommit

#----------------------------------------------------------------------------
# Setup test environment
test-configuration:
 stage: Configure
 script:
  - clang++ --verbose
  - clang++ --verbose 2>&1 > /dev/null | grep "Found CUDA installation"
  - clang++ --verbose 2>&1 > /dev/null | grep "Found CUDA installation" | grep "version unknown" || exit 0
  - exit 1
 <<: *cache
 <<: *restrict_precommit


#----------------------------------------------------------------------------
# Setup test environment
build:
 stage: Build
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} ccache --zero-stats
  - CCACHE_DIR=${ccache_dir} CCACHE_NOHASHDIR=1 CCACHE_BASEDIR=${build_path} cmake --build ${build_path} --target all -- -j`nproc --all`
  - CCACHE_DIR=${ccache_dir} ccache --show-stats
  - echo "Building... done"
 <<: *cache
 <<: *restrict_precommit

install:
 stage: Install
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - echo "Installing... done"
 <<: *cache
 <<: *restrict_precommit

#----------------------------------------------------------------------------
# Functional Tests
Test 01 - Threads:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-threads --gtest_output="xml:$CWD/report-threads.xml"
 artifacts:
  reports:
   junit: report-threads.xml

Test 02 - Plan Parsing:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-plan-parsing --gtest_output="xml:$CWD/report-plan-parsing.xml"
 artifacts:
  reports:
   junit: report-plan-parsing.xml

Test 03 - JSON:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-json --gtest_output="xml:$CWD/report-json.xml"
 allow_failure: true
 artifacts:
  reports:
   junit: report-json.xml

Test 04 - Joins:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-joins --gtest_output="xml:$CWD/report-joins.xml"
 allow_failure: true
 artifacts:
  reports:
   junit: report-joins.xml

Test 05 - Output:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-output --gtest_output="xml:$CWD/report-output.xml"
 artifacts:
  reports:
   junit: report-output.xml

Test 06 - GPU SSB SF100:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-gpu-ssb --gtest_output="xml:$CWD/report-gpu.xml"
 artifacts:
  reports:
   junit: report-gpu.xml

Test 07 - CPU SSB SF100:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-cpu-ssb --gtest_output="xml:$CWD/report-cpu.xml"
 artifacts:
  reports:
   junit: report-cpu.xml

Test 08 - Hybrid SSB SF100:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-hyb-ssb --gtest_output="xml:$CWD/report-hyb.xml"
 artifacts:
  reports:
   junit: report-hyb.xml

Test 09 - COW:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && ./unit-tests-cow --gtest_output="xml:$CWD/report-cow.xml"
 artifacts:
  reports:
   junit: report-cow.xml

Test 10 - Planner:
 <<: *test
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - ln -s ${build_path}/opt/pelago/inputs ${build_path}/core/planner/CMakeFiles/clotho.dir/inputs
  - export CWD=$(pwd)
  - export OUTPUT=0
  - cd ${build_path}/core/planner/CMakeFiles/clotho.dir && sbt test || export OUTPUT=1
  - mv ${build_path}/core/planner/CMakeFiles/clotho.dir/target/test-reports/TEST-*.xml $CWD
  - exit $OUTPUT
 allow_failure: true
 artifacts:
  reports:
   junit: TEST-*.xml


#----------------------------------------------------------------------------
# Performance Tests
# unhide the jobs by removing the leading '.'
.bench:
 stage: Benchmark
 script:
  - echo "Bench... done"
 <<: *cache
 <<: *restrict_precommit

SSB100 Benchmark - CPU only:
 stage: Benchmark
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && java -jar ../../opt/lib/clotho.jar --server inputs/plans/schema.json & disown && sleep 30
  - echo "select sum(d_datekey) from ssbm_date;" > queries.sql
  - echo "alter session set hwmode=cpuonly;" >> queries.sql
  - for f in core/planner/src/test/resources/tests/ssb100/queries/q*.sql; do cat $f $f $f $f $f >> queries.sql ; done ;
  - echo "select * from SessionTimings ;" >> queries.sql
  - JAVA_CLASSPATH=/avatica-1.13.0.jar sqlline --color=true --maxWidth=1024 -u "jdbc:avatica:remote:url=http://localhost:8081;serialization=PROTOBUF" < queries.sql
  - JAVA_AVATICA_CLASSPATH=/avatica-1.13.0.jar python ./tools/save_session_timings.py
 <<: *cache
 <<: *restrict_precommit

SSB100 Benchmark - GPU only:
 stage: Benchmark
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && java -jar ../../opt/lib/clotho.jar --server inputs/plans/schema.json & disown && sleep 30
  - echo "select sum(d_datekey) from ssbm_date;" > queries.sql
  - echo "alter session set hwmode=gpuonly;" >> queries.sql
  - for f in core/planner/src/test/resources/tests/ssb100/queries/q*.sql; do cat $f $f $f $f $f >> queries.sql ; done ;
  - echo "select * from SessionTimings ;" >> queries.sql
  - JAVA_CLASSPATH=/avatica-1.13.0.jar sqlline --color=true --maxWidth=1024 -u "jdbc:avatica:remote:url=http://localhost:8081;serialization=PROTOBUF" < queries.sql
  - JAVA_AVATICA_CLASSPATH=/avatica-1.13.0.jar python ./tools/save_session_timings.py
 <<: *cache
 <<: *restrict_precommit

SSB100 Benchmark - Hybrid:
 stage: Benchmark
 script:
  - ccache_dir=$(pwd | sed "s/^\/builds/\/cache/g")/.ccache
  - build_path=$(pwd | sed "s/^\/builds/\/cache/g")/${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}/cmake-build-debug
  - mkdir -p ${build_path}
  - CCACHE_DIR=${ccache_dir} cmake --build ${build_path} --target install
  - export CWD=$(pwd)
  - cd ${build_path}/opt/pelago && java -jar ../../opt/lib/clotho.jar --server inputs/plans/schema.json & disown && sleep 30
  - echo "select sum(d_datekey) from ssbm_date;" > queries.sql
  - echo "alter session set hwmode=hybrid;" >> queries.sql
  - for f in core/planner/src/test/resources/tests/ssb100/queries/q*.sql; do cat $f $f $f $f $f >> queries.sql ; done ;
  - echo "select * from SessionTimings ;" >> queries.sql
  - JAVA_CLASSPATH=/avatica-1.13.0.jar sqlline --color=true --maxWidth=1024 -u "jdbc:avatica:remote:url=http://localhost:8081;serialization=PROTOBUF" < queries.sql
  - JAVA_AVATICA_CLASSPATH=/avatica-1.13.0.jar python ./tools/save_session_timings.py
 <<: *cache
 <<: *restrict_precommit

#----------------------------------------------------------------------------
# Execution Profiling 
# unhide the jobs by removing the leading '.'
.build profile:
 stage: Build Profile
 script:
  - echo "Building Dependencies... done"
  - echo "Building... done"
  - echo "Installing... done"
 when: manual
 <<: *cache_profile
 <<: *restrict_precommit

.1/2 profile:
 stage: Profile
 script:
  - echo "Running workload 1... done"
  - echo "Extracting profiling statistics"
 when: manual
 cache:
  policy: pull
 <<: *cache_profile
 <<: *restrict_precommit

.2/2 profile:
 stage: Profile
 script:
  - echo "Running workload 2... done"
  - echo "Extracting profiling statistics"
 when: manual
 cache:
  policy: pull
 <<: *cache_profile
 <<: *restrict_precommit

#----------------------------------------------------------------------------
# Packaging & distribution
.tar:
 stage: Package
 script:
  - echo "Generating tar... done"
 <<: *cache
 <<: *restrict_postcommit

.tar:latest:
 stage: Publish
 script:
  - echo "Publishing HEAD... done"
 artifacts:
  name: "$CI_PROJECT_NAME-g$CI_COMMIT_SHA"
  paths:
   - pkg/
 cache:
  policy: pull
 <<: *cache
 <<: *restrict_latest

.tar:release:
 stage: Publish
 script:
  - echo "Publishing release... done"
 artifacts:
  name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG"
  paths:
   - pkg/
 cache:
  policy: pull
 <<: *cache
 <<: *restrict_release
